version: "3.9"

services:

  logindb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Passw0rd!
    volumes:
      - ./volumes/LoginDB:/var/opt/mssql/data

  menudb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1434:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Passw0rd!
    volumes:
      - ./volumes/MenuDB:/var/opt/mssql/data

  paymentdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1435:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Passw0rd!
    volumes:
      - ./volumes/PaymentDB:/var/opt/mssql/data

  loginservice:
    build: ./LoginService
    image: nettanljungkvist/loginservice
    restart: always
    ports:
      - 5000:80
    depends_on:
      - logindb

  menuservice:
    build: ./MenuService
    image: nettanljungkvist/menuservice
    restart: always
    ports:
      - 5001:80
    depends_on:
      - menudb
  
  paymentservice:
    build: ./PaymentService
    image: nettanljungkvist/paymentservice
    restart: always
    ports:
      - 5002:80
    depends_on:
      - paymentdb